// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7g7NeLUXImbrk5paCTx4dwT8K3Vvxg2c',
    appId: '1:1048115043892:web:c3f441c3515b8184733461',
    messagingSenderId: '1048115043892',
    projectId: 'online-food-delivery-app-b5bc1',
    authDomain: 'online-food-delivery-app-b5bc1.firebaseapp.com',
    storageBucket: 'online-food-delivery-app-b5bc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANMcAUdD70DBHrff8EGXZ1u8BDfyxBYxI',
    appId: '1:1048115043892:android:e45e467b5600129c733461',
    messagingSenderId: '1048115043892',
    projectId: 'online-food-delivery-app-b5bc1',
    storageBucket: 'online-food-delivery-app-b5bc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd2XcejdqNLL_QXX3trV4dsW6gwaPy0z0',
    appId: '1:1048115043892:ios:09b62ad7e9d309ca733461',
    messagingSenderId: '1048115043892',
    projectId: 'online-food-delivery-app-b5bc1',
    storageBucket: 'online-food-delivery-app-b5bc1.appspot.com',
    iosBundleId: 'com.example.onlineFoodDeliveryApp',
  );
}
